name: creatures
description: Console game in dart and aditional examples.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  console: ^4.1.0
  ncurses: ^0.1.0
  vector_math: ^2.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
